require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'serviceApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-razorpay', :path => '../node_modules/react-native-razorpay'


  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'serviceAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'serviceApp-tvOS' do
  # Pods for serviceApp-tvOS

  target 'serviceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
